services:
  offcloudarr:
    image: supergraham/offcloudarr:latest
    container_name: offcloudarr
    environment:
      - OFFCLOUD_API_KEY=YOUR_OFFCLOUD_API_KEY
      - OFFCLOUD_STORAGE=cloud
      - POLL_INTERVAL=10
      - BLACKHOLE_DIRS=/sonarr-blackhole,/radarr-blackhole
    volumes:
      - /opt/docker/sonarr/blackhole:/sonarr-blackhole
      - /opt/docker/radarr/blackhole:/radarr-blackhole
    ports:
      - 6771:6771
    restart: unless-stopped
